config/routes.rb
Rails.application.routes.draw do
  resources :items
  get 'menu' => 'menu#index'
  # root 'menu#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	enum kind: [ :food, :drink]

	validates :title, presence: true
	validates :price, presence: true, numericality: { greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :price)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @drinks = Item.drink
    @food = Item.food
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :title, class: 'col-12 col-sm-2 col-form-label' %>
    <div class="col-12 col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :price, class: 'col-12 col-sm-2 col-form-label' %>
    <div class="col-12 col-sm-10">
      <%= f.text_field :price, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<%= item.title %> · <%= number_to_currency item.price %>
<% if local_assigns.fetch(:show_order, false) %>
    · <%= link_to 'Order', new_order_path(item: item.id) %>
<% end %>

app/views/items/edit.html.erb
<h1 class="text-center mt-2">Editing Item</h1>

<%= render 'form', item: @item %>

<div class="btn-group">
    <%= link_to 'Show', @item, class: 'btn' %>
    <%= link_to 'Back', items_path, class: 'btn' %>
</div>

app/views/items/index.html.erb
<div id="notice"><%= notice %></div>

<h1 class="text-center mt-3 mb-2">Items</h1>

<section class="card-group">
  <% @items.each do |item| %>
    <div class="card text-center mb-3">
      <div class="card-block">
        <%= link_to item do %>
          <h4 class="card-title"><%= render item %></h4>
        <% end %>
      </div>
      <div class="card-footer">
        <div class="btn-group">
          <%= link_to 'Edit', edit_item_path(item), class: 'btn btn-sm btn-outline-primary' %>
          <%= link_to 'Destroy', item, method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>
</section>

<div class="mt-2 mb-4 text-center">
  <div class="btn-group">
    <%= link_to 'New Item', new_item_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/items/new.html.erb
<h1 class="text-center mt-2">New Item</h1>

<%= render 'form', item: @item %>

<div class="btn-group">
    <%= link_to 'Back', items_path, class: 'btn' %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe on Rails</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container-fluid">
      <%= yield %>
    </main>
  </body>
</html>

app/views/menu/index.html.erb
<h1 class="text-center mt-2">Menu</h1>

<h2 class="text-center mt-3">Drinks</h2>
<ul class="nav flex-column text-center">
  <% @drinks.each do |item| %>
    <li class="nav-item"><%= render item, show_order: true %></li>
  <% end %>
</ul>

<h2 class="text-center mt-3">Food</h2>
<ul class="nav flex-column text-center">
  <% @food.each do |item| %>
    <li class="nav-item"><%= render item, show_order: true %></li>
  <% end %>
</ul>